### ISSUE TITLE
Verwendung

### ISSUE THREAD

**Issue by Silverridge-AE** [bmgjet/RustMapResizer#1]
Hallo. Wie genau muss ich veränderungen am server vornehmen das die neue Map arbeitet? Ich habe bereits die Map wie beschrieben vergrößert. Wie aber muss ich weiter machen das die neue Map auf dem Server arbeitet?

**Comment by bmgjet** [comment]
Edit map with tool.
Work on map with rust edit.
Enter line of code in a plugin on the server to force it to your size.
